# This is a basic workflow to help you get started with Actions

name: CT-tests (Clang and Clang-15)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "github" branch
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ct:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
          clang_config: [CTOS, CTO0, CTO2, CTO3, CTOSNOVEC, CTO0NOVEC, CTO2NOVEC, CTO3NOVEC]
          # TODO: valgrind seems buggy with CT01 and CT01NOVEC
          clang_version: [clang, clang-15]
  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: sudo apt update && sudo apt -y install build-essential valgrind cmake libboost-tools-dev libpthread-stubs0-dev libssl-dev clang-15 clang gcc gcc-12

      - name: CT-Test (clang)
        run: |
            ldd --version
            rm -rf build && mkdir build && cd build && cmake -DCMAKE_C_COMPILER=${{ matrix.clang_version }} -DMLCA_NO_VALGRIND=OFF -DCMAKE_BUILD_TYPE=${{ matrix.clang_config }} .. && make -j
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test ML-DSA-44 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test ML-DSA-65 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test ML-DSA-87 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Dilithium2 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Dilithium3 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Dilithium5 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Dilithium54_R2 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Dilithium65_R2 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Dilithium87_R2 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test ML-KEM-768 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test ML-KEM-1024 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Kyber768 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Kyber1024 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Kyber768_R2 self_const
            valgrind --tool=memcheck --gen-suppressions=all --error-exitcode=1 --suppressions=../test/ct-passes test/mlca_test Kyber1024_R2 self_const
            cd ..
